# -*- coding: utf-8 -*-
"""
Case Study Parameters
======================
Documents the Manual_Input.py settings used for the two MUKERC case studies:
  1. ASC Reduction Sweep  — seven runs across a range of Agreed Supply Capacities
  2. TOU Demand Shifting  — thirteen runs across four shift directions and three
                            magnitudes, plus an unshifted baseline

This file is a reference document, not an executable pipeline script. To reproduce
a case study run, copy the relevant parameter values into Manual_Input.py, set
run_mode = 'Specific', and execute Post Analysis.py.

For the TOU Demand Shifting scenarios, the 12 shifted demand profile files must
first be generated by running Generate_TOU_Shift_Profiles.py.

Fixed Manual_Input.py settings — common to ALL case study runs below
----------------------------------------------------------------------
    run_mode        = 'Specific'
    vol_type        = 'HV'
    has_mic         = True
    residual_band   = 'Band 4'
    specific_regions = ['12 - London.xlsx']
    power_factor    = 0.98
    start_year      = 2017
    end_year_limit  = 2026

The `case_study_name` value creates a subfolder under
    Output Data Repository/Case Studies/<case_study_name>/
Use forward slashes to create a subfolder hierarchy (e.g. 'GroupName/RunName').
"""

# ── Case Study 1: ASC Reduction Sweep ────────────────────────────────────────
# Seven runs holding the demand profile constant (ICL 2016) and varying the
# Agreed Supply Capacity (basis, kVA) from 11,500 to 17,500 in 1,000 kVA steps.
# The 16,500 kVA run is the reference scenario matching the site's actual ASC.
#
# For each run, set in Manual_Input.py:
#   demand_profile_file = 'Imperial College London 2016 Demand Profile.xlsx'
#   basis               = <value from table below>
#   case_study_name     = <value from table below>

ASC_SWEEP_SCENARIOS = [
    {'case_study_name': 'Chapter 5 - ASC Reduction/ASC Sweep - 11500', 'basis': 11500},
    {'case_study_name': 'Chapter 5 - ASC Reduction/ASC Sweep - 12500', 'basis': 12500},
    {'case_study_name': 'Chapter 5 - ASC Reduction/ASC Sweep - 13500', 'basis': 13500},
    {'case_study_name': 'Chapter 5 - ASC Reduction/ASC Sweep - 14500', 'basis': 14500},
    {'case_study_name': 'Chapter 5 - ASC Reduction/ASC Sweep - 15500', 'basis': 15500},
    {'case_study_name': 'Chapter 5 - ASC Reduction/ASC Sweep - 16500', 'basis': 16500},  # reference
    {'case_study_name': 'Chapter 5 - ASC Reduction/ASC Sweep - 17500', 'basis': 17500},
]


# ── Case Study 2: TOU Demand Shifting ────────────────────────────────────────
# Thirteen runs: one unshifted baseline and twelve shifted variants.
# All runs use basis = 16500 (site ASC) and vary the demand_profile_file only.
#
# The 12 shifted profile files are produced by Generate_TOU_Shift_Profiles.py.
# Run that script first if the files are not already present in
# Input/Case Study Demand Profiles/.
#
# Shift directions:
#   Fwd1h  — demand moved forward by 1 hour (16:00-18:30 -> 17:00-19:30)
#   Back1h — demand moved back by 1 hour    (16:00-18:30 -> 15:00-17:30)
#   Back2h — demand moved back by 2 hours   (16:00-18:30 -> 14:00-16:30)
#   Back3h — demand moved back by 3 hours   (16:00-18:30 -> 13:00-15:30)
#
# Magnitudes: 10%, 20%, 30% of Red-band demand relocated per half-hour

TOU_SHIFT_SCENARIOS = [
    # Baseline — unshifted
    {'case_study_name': 'Chapter 5 - TOU Shift/TOU Shift - Baseline',
     'demand_profile_file': 'Imperial College London 2016 Demand Profile.xlsx',
     'basis': 16500},

    # Fwd 1h
    {'case_study_name': 'Chapter 5 - TOU Shift/TOU Shift - Fwd1h - 10pct',
     'demand_profile_file': 'ICL 2016 TOU Shift Fwd1h 10pct.xlsx', 'basis': 16500},
    {'case_study_name': 'Chapter 5 - TOU Shift/TOU Shift - Fwd1h - 20pct',
     'demand_profile_file': 'ICL 2016 TOU Shift Fwd1h 20pct.xlsx', 'basis': 16500},
    {'case_study_name': 'Chapter 5 - TOU Shift/TOU Shift - Fwd1h - 30pct',
     'demand_profile_file': 'ICL 2016 TOU Shift Fwd1h 30pct.xlsx', 'basis': 16500},

    # Back 1h
    {'case_study_name': 'Chapter 5 - TOU Shift/TOU Shift - Back1h - 10pct',
     'demand_profile_file': 'ICL 2016 TOU Shift Back1h 10pct.xlsx', 'basis': 16500},
    {'case_study_name': 'Chapter 5 - TOU Shift/TOU Shift - Back1h - 20pct',
     'demand_profile_file': 'ICL 2016 TOU Shift Back1h 20pct.xlsx', 'basis': 16500},
    {'case_study_name': 'Chapter 5 - TOU Shift/TOU Shift - Back1h - 30pct',
     'demand_profile_file': 'ICL 2016 TOU Shift Back1h 30pct.xlsx', 'basis': 16500},

    # Back 2h
    {'case_study_name': 'Chapter 5 - TOU Shift/TOU Shift - Back2h - 10pct',
     'demand_profile_file': 'ICL 2016 TOU Shift Back2h 10pct.xlsx', 'basis': 16500},
    {'case_study_name': 'Chapter 5 - TOU Shift/TOU Shift - Back2h - 20pct',
     'demand_profile_file': 'ICL 2016 TOU Shift Back2h 20pct.xlsx', 'basis': 16500},
    {'case_study_name': 'Chapter 5 - TOU Shift/TOU Shift - Back2h - 30pct',
     'demand_profile_file': 'ICL 2016 TOU Shift Back2h 30pct.xlsx', 'basis': 16500},

    # Back 3h
    {'case_study_name': 'Chapter 5 - TOU Shift/TOU Shift - Back3h - 10pct',
     'demand_profile_file': 'ICL 2016 TOU Shift Back3h 10pct.xlsx', 'basis': 16500},
    {'case_study_name': 'Chapter 5 - TOU Shift/TOU Shift - Back3h - 20pct',
     'demand_profile_file': 'ICL 2016 TOU Shift Back3h 20pct.xlsx', 'basis': 16500},
    {'case_study_name': 'Chapter 5 - TOU Shift/TOU Shift - Back3h - 30pct',
     'demand_profile_file': 'ICL 2016 TOU Shift Back3h 30pct.xlsx', 'basis': 16500},
]
